apiVersion: v1
entries:
  cyclops-chart:
  - apiVersion: v2
    appVersion: v0.15.4
    created: "2024-12-30T16:33:14.242168775Z"
    description: Cyclops Helm chart
    digest: 1630813c12b46c757b1d79283e627b06ad16d591cb7edf589a78138cc66d57f7
    home: https://cyclops-ui.com/
    keywords:
    - Devops
    - Kubernetes operator
    name: cyclops-chart
    type: application
    urls:
    - https://cyclops-ui.github.io/helm/cyclops-chart-0.12.0.tgz
    version: 0.12.0
generated: "2024-12-30T16:33:14.241732063Z"
